const datalog = [
   {
      ADASBUS: {
         FCM: {
            FCMCalibrationStatus: {
               displayValue: "100V",
               minValue: 200,
               maxValue: 400,
               value: 100,
               unit: "Volt",
               def: "The state-of-charge shows the amount of electric charge left in the battery",
            },
         },
         ADAS: {
            RightSVCCalibrationStatus: {
               displayValue: "80C",
               minValue: 0,
               maxValue: 100,
               value: 80,
               unit: "deg/C",
               def: "The state-of-charge shows the amount of electric charge left in the battery",
            },
            RearSVCCalibrationStatus: {
               displayValue: "6.3V",
               minValue: 0,
               maxValue: 5,
               value: 6.3,
               unit: "Volt",
               def: "The state-of-charge shows the amount of electric charge left in the battery",
            },
            LeftSVCCalibrationStatus: {
               displayValue: "82C",
               minValue: 0,
               maxValue: 90,
               value: 82,
               unit: "deg/C",
               def: "The state-of-charge shows the amount of electric charge left in the battery",
            },
            FrontSVCCalibrationStatus: {
               displayValue: "3600 rpm",
               minValue: 0,
               maxValue: 5000,
               value: 3600,
               unit: "rpm",
               def: "The state-of-charge shows the amount of electric charge left in the battery",
            },
         },
         CMRR_FL: {
            FrontLeftRadarCalibrationStatus: {
               displayValue: "3600 rpm",
               minValue: 0,
               maxValue: 5000,
               value: 3600,
               unit: "rpm",
               def: "The state-of-charge shows the amount of electric charge left in the battery",
            },
            RearLeftRadarCalibrationStatus: {
               displayValue: "82C",
               minValue: 0,
               maxValue: 90,
               value: 82,
               unit: "deg/C",
               def: "The state-of-charge shows the amount of electric charge left in the battery",
            },
            RearRightRadarCalibrationStatus: {
               displayValue: "208V",
               minValue: 200,
               maxValue: 400,
               value: 208,
               unit: "Volt",
               def: "The state-of-charge shows the amount of electric charge left in the battery",
            },
            FrontRightRadarCalibrationStatus: {
               displayValue: "100V",
               minValue: 200,
               maxValue: 400,
               value: 100,
               unit: "Volt",
               def: "The state-of-charge shows the amount of electric charge left in the battery",
            },
         },
      },
      CBUS: {
         CBUS: {
            WheelSpeedLR: {
               displayValue: "30kph",
               minValue: 0,
               maxValue: 100,
               value: 30,
               unit: "kph",
               def: "The state-of-charge shows the amount of electric charge left in the battery",
            },
            SteeringAngle: {
               displayValue: "75C",
               minValue: 0,
               maxValue: 100,
               value: 75,
               unit: "deg/C",
               def: "The state-of-charge shows the amount of electric charge left in the battery",
            },
            VehicleSpeed: {
               displayValue: "50kph",
               minValue: 10,
               maxValue: 200,
               value: 50,
               unit: "kph",
               def: "The state-of-charge shows the amount of electric charge left in the battery",
            },
            WheelSpeedLF: {
               displayValue: "70kph",
               minValue: 100,
               maxValue: 200,
               value: 10,
               unit: "kph",
               def: "The state-of-charge shows the amount of electric charge left in the battery",
            },
         },
      },
      EVBUS: {
         ESP: {
            WheelSpeedRR: {
               displayValue: "208V",
               minValue: 200,
               maxValue: 400,
               value: 208,
               unit: "Volt",
               def: "The state-of-charge shows the amount of electric charge left in the battery",
            },
            VehicleSpeed: {
               displayValue: "82C",
               minValue: 0,
               maxValue: 90,
               value: 82,
               unit: "deg/C",
               def: "The state-of-charge shows the amount of electric charge left in the battery",
            },
            WheelSpeedLF: {
               displayValue: "10A",
               minValue: 20,
               maxValue: 40,
               value: 10,
               unit: "Amp",
               def: "The state-of-charge shows the amount of electric charge left in the battery",
            },
         },
         ICC: {
            Odometer: {
               displayValue: "3600 rpm",
               minValue: 0,
               maxValue: 5000,
               value: 3600,
               unit: "rpm",
               def: "The state-of-charge shows the amount of electric charge left in the battery",
            },
         },
         BMS: {
            MaxCellVoltage: {
               displayValue: "100V",
               minValue: 200,
               maxValue: 400,
               value: 100,
               unit: "Volt",
               def: "The state-of-charge shows the amount of electric charge left in the battery",
            },
            HVILFaultState: {
               displayValue: "35%",
               minValue: 25,
               maxValue: 100,
               value: 35,
               unit: "%",
               def: "The state-of-charge shows the amount of electric charge left in the battery",
            },
            ContactorState: {
               displayValue: "30A",
               minValue: 20,
               maxValue: 40,
               value: 30,
               unit: "Amp",
               def: "The state-of-charge shows the amount of electric charge left in the battery",
            },
            BMSState: {
               displayValue: "400V",
               minValue: 300,
               maxValue: 500,
               value: 400,
               unit: "Volt",
               def: "The state-of-charge shows the amount of electric charge left in the battery",
            },
         },
      },
   },
];
export default datalog;
