// Storage Keys
export const VIN_DATA_STORE = "VIN_DATA_STORE";
export const ACTIVE_VIN_DATA_STORE = "ACTIVE_VIN_DATA_STORE";
export const USER_TOKEN_DATA_STORE = "USER_TOKEN_DATA_STORE";
export const PARAM_STORE = "PARAM_STORE";
export const USER_DETAIL_DATA_STORE = "USER_DETAIL_DATA_STORE";

export const OFFLINE_SYNC_DATA = "OFFLINE_SYNC_DATA";
export const VEHICLE_CONFIGURATION_DATA_STORE =
   "VEHICLE_CONFIGURATION_DATA_STORE";
export const LOCAL_AUTH_TOKEN_DATA = "LOCAL_AUTH_TOKEN_DATA";
export const SERVICE_SESSION_DATA = "SERVICE_SESSION_DATA";
export const VEHICLE_FLASHING_DATA = "VEHICLE_FLASHING_DATA";

export const HISTORY_CONFIG_ACTION = "HISTORY_CONFIG_ACTION";
export const HISTORY_STATION_ACTION = "HISTORY_STATION_ACTION";
