export const SELECTED_TOOL = "SELECTED_TOOL";
export const List_Of_Tool = {
   COMPONENTS_FLASHING: "COMPONENTS FLASHING",
   TEST_BENCH: "TEST BENCH",
   VEHICLE_EOL: "VEHICLE EOL",
   MANUFACTURING_STATION: "MANUFACTURING STATION",
};
