export const allImages = {
   createIcon: require("../../src/assets/images/create.png"),
   modifyIcon: require("../../src/assets/images/modify.png"),
   syncIcon: require("../../src/assets/images/file-sync.png"),
   configurationIcon: require("../../src/assets/images/configurator.png"),
   homeIcon: require("../../src/assets/images/home-button.png"),
   folderIcon: require("../../src/assets/images/open-folder.png"),
   downArrowIcon: require("../../src/assets/images/downarrow.png"),
   deleteIcon: require("../../src/assets/images/delete.png"),
   arrowUDIcon: require("../../src/assets/images/arrow-ud.png"),
   addIcon: require("../../src/assets/images/add.png"),
   saveIcon: require("../../src/assets/images/carbon_save.png"),
   undoRightIcon: require("../../src/assets/images/undo.png"),
   undoBackIcon: require("../../src/assets/images/undo.png"),
   arrowSyncIcon: require("../../src/assets/images/arrow-sync.png"),
   playIcon: require("../../src/assets/images/play.png"),
   addRoundIcon: require("../../src/assets/images/add-round.png"),
   plusSmallIcon: require("../../src/assets/images/plus-small.png"),
   formKitIcon: require("../../src/assets/images/formkit.png"),
   deleteToolIcon: require("../../src/assets/images/delete-tool.png"),
   materialSymbolsIcon: require("../../src/assets/images/material-symbols.png"),
   editingIcon: require("../../src/assets/images/editing.png"),
   copyIcon: require("../../src/assets/images/copy.png"),
   closeCircleIcon: require("../../src/assets/images/close-circle.png"),
};
